- name: Import OS family specific vars
  include_vars: "vars/{{ ansible_os_family.lower() }}.yml"

- name: Install required packages
  package:
    state: present
    name: "{{ relaymail_packages }}"

- name: Add postfix config files
  template: src={{ item }} dest=/etc/postfix/ owner=root group=root mode=644
  with_items:
    - main.cf
    - master.cf
    - recipient_canonical_maps
    - sender_canonical_maps
  notify: restart postfix

- name: Add secret auth
  template: src=sasl_passwd dest=/etc/postfix owner=root group=root mode=600
  register: sasl_hash_results
  when: relaymail_smtp_user is defined
  notify: restart postfix

# lookup table type "regexp" doesn't need to be hashed according to "man postmap"
- name: postmap sasl hastable
  command: postmap /etc/postfix/sasl_passwd
  when: sasl_hash_results is changed

- name: Add empty rc.local if it doesn't exist
  copy:
    src: rc.local
    dest: /etc/rc.local
    mode: 700
    owner: root
    group: root
    force: no
  when: relaymail_restrict_port_25

- name: Create rc.local_ansible_relaymail file with iptables rules
  template:
    src: rc.local_ansible_relaymail
    dest: /etc/rc.local_ansible_relaymail
    mode: 700
    owner: root
  when: relaymail_restrict_port_25
  register: __relaymail_rc_local

- name: Execute /etc/rc.local_ansible_relaymail if if has been changed
  shell: /etc/rc.local_ansible_relaymail
  when: __relaymail_rc_local is changed

- name: Ensure rc.local_ansible_relaymail file is included in rc.local
  lineinfile:
    dest: /etc/rc.local
    line: "bash /etc/rc.local_ansible_relaymail"
    insertbefore: "exit 0"
    state: "{{ relaymail_restrict_port_25 | ternary('present', 'absent') }}"

